---

- hosts: all
  become: true
  tasks: 

# Ubuntu y Debian

  - name: Instalar Apache2+PHP
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]


# CentOS

  - name: Instalar Apache2+PHP
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

            