---

- hosts: all
  become: true
  pre_tasks: 

  - name: install updates (CentOS)
    tags: always
    dnf: 
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
    
  - name: install updates (Ubuntu)
    tags: always
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]
    
- hosts: workstations
  become: true
  tasks: 
  
  - name: install unzip
    package:
      name: unzip
      
  - name: install terraform
    unarchive: 
      src: https://releases.hashicorp.com/terraform/0.14.2/terraform_0.14.2_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: Instalar Apache2+PHP en sistemas Debian y Ubuntu
    tags: apache, apache2, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: Instalar Apache2+PHP en sistemas CentOS
    tags: apache, centos, httpd
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
    
  - name: Copia de la página de inicio por defecto
    tags: apache, apache2, httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  
  - name: Instalar MariaDB en CentOS
    tags: centos, db, mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"
    
  - name: Instlar MariaDB en Ubuntu o Debian
    tags: db, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  tasks:
  
  - name: instalar samba en Debian
    tags: samba
    package: 
      name: samba
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
         